### ISSUE TITLE
RQ反向同步

### ISSUE THREAD

**Issue by L1cardo** [NaturezzZ/GarminSync#1]
您好，我有看到您写了关于RQ的[相关代码](https://github.com/NaturezzZ/GarminSync/blob/89dc00c19cce63fb5848d2a16010d42ec74c5159/src/utils/runningquotient.ts)，但是我不太能看懂Python，想请问能否将RQ的相关数据反向同步到Strava或者Garmin？
谢谢！

**Comment by NaturezzZ** [comment]
Please refer to https://gitlab.com/gooin/dailysync to seek original developers for help.
